# Hands on Numpy 

* **import numpy it is rarely used to access any function in numpy you have to use numpy.function_name**

In [1]:
import warnings; warnings.simplefilter('ignore') # To make life easier
import numpy as np 

# Creating N-Dimensional Array 

In [2]:
data=[1,2,55,3.2,6,99,10,0.05]

In [3]:
arr1=np.array(data)

In [4]:
arr1

array([  1.00000000e+00,   2.00000000e+00,   5.50000000e+01,
         3.20000000e+00,   6.00000000e+00,   9.90000000e+01,
         1.00000000e+01,   5.00000000e-02])

In [5]:
arr1.shape

(8L,)

In [6]:
arr1.dtype

dtype('float64')

In [7]:
data2=[[1,2,3],[4,5,6]]

In [8]:
arr2=np.array(data2)

In [9]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr2.shape #(returns no of rows,no of columns)

(2L, 3L)

In [11]:
arr2_re=arr2.reshape((3,2)) #input parameter : tuple consisting new dimensions of rows and columns 
arr2_re


array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr2.dtype

dtype('int32')

 **There are inbuilt functions to create ndarrays**

In [13]:
zero_arr=np.zeros((2,2)) #creates an 2 X 2 array of zeros 

In [14]:
zero_arr

array([[ 0.,  0.],
       [ 0.,  0.]])

In [15]:
ones_arr = np.ones((2,2))    # Create an array of all ones

In [16]:
ones_arr

array([[ 1.,  1.],
       [ 1.,  1.]])

In [17]:
const_arr = np.full((2,2), 7)  # Create a constant array

In [18]:
const_arr

array([[7, 7],
       [7, 7]])

In [19]:
identity_arrr = np.eye(3)  # Create a 2x2 identity matrix

In [20]:
identity_arrr

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
random_arr = np.random.random((3,3)) #Create an array filled with random values

In [22]:
random_arr

array([[ 0.61212015,  0.19101688,  0.14490132],
       [ 0.66533534,  0.67833124,  0.97776709],
       [ 0.02569103,  0.3534347 ,  0.83989189]])

# Array indexing

**Numpy offers several ways to index into arrays.**

* Slicing: Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array

In [23]:
# Create the following rank 2 array with shape (3, 4)
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
b=a[:2,1:3]
b

array([[2, 3],
       [6, 7]])

*  A slice of an array is a view into the same data, so modifying it will modify the original array.

In [25]:
a[0,1]

2

In [26]:
b[0,0]

2

In [27]:
b[0,0]=77

In [28]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
bool_indx=(a > 4)
bool_indx

array([[False,  True, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [30]:
a[bool_indx]

array([77,  5,  6,  7,  8,  9, 10, 11, 12])

In [31]:
a[a>4]

array([77,  5,  6,  7,  8,  9, 10, 11, 12])

* **There are numpy defined data types** 

<img src="pictures/Capture.JPG">

In [32]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [35]:
x+y

array([[  6.,   8.],
       [ 10.,  12.]])

In [36]:
np.add(x,y)

array([[  6.,   8.],
       [ 10.,  12.]])

In [37]:
np.sqrt(x)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ]])

In [38]:
#Vectors
v = np.array([9,10])
w = np.array([11, 12])

v.dot(w)

219

In [39]:
np.dot(v,w)

219

In [40]:
x = np.array([[1,2],[3,4]])

In [41]:
np.sum(x)

10

In [42]:
np.sum(x,axis=0)

array([4, 6])

In [43]:
np.sum(x,axis=1)

array([3, 7])

In [44]:
x = np.array([[1,2], [3,4]])

In [45]:
x

array([[1, 2],
       [3, 4]])

In [46]:
x.T

array([[1, 3],
       [2, 4]])

* **Numpy Linear Algebra Functions**

In [47]:
from numpy.linalg import eigvals,det

In [50]:
X =  np.random.random((5, 5))

In [51]:
X

array([[ 0.99696786,  0.17431973,  0.97257875,  0.4005911 ,  0.46750505],
       [ 0.45315036,  0.9888067 ,  0.72104623,  0.97528095,  0.91057374],
       [ 0.64682981,  0.63252436,  0.24320633,  0.19325903,  0.36273312],
       [ 0.93789726,  0.81043943,  0.24185795,  0.65617557,  0.92141021],
       [ 0.96169844,  0.28371627,  0.41282294,  0.85311662,  0.73279511]])

In [49]:
eigvals(X)

array([ 2.58106954, -0.90993926, -0.54639056,  0.16762049, -0.17854646])

In [52]:
det(X)

0.088628488942919983

* **The linspace Function**

Returns evenly spaced numbers over a specified interval in an ndarray.

In [53]:
np.linspace(2.0, 3.0, num=5)

array([ 2.  ,  2.25,  2.5 ,  2.75,  3.  ])